### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [mazmaz2k/jlm.fm#3]
- לא תייגתם אותי בissue שפתחתם
- אין שונות בין חברי הצוות ומידע על חברי הצוות
- חסר סיכונים שקשורים בפרויקט עצמו

**Comment by Zvukamar** [comment]
היי קובי
כן עשינו הכל משכתבת בהערות,
ניתן לראות את זה ב
WIKI-TEAM (מידע ושונות על חברי הצוות)
WIKI-INCEPTION PLANNING (מידע על הסיכונים ועל דרך ניהול הפרוייקט)
@kob-e

**Comment by YaakovHatam** [comment]
1. @Zvukamar שים לב להוראת לפתיחת issue:
> פתיחת משימה (issue) במאגר הקורס בשם: Check Project 2 Submission ושיוכה למתרגל (הסבר בהמשך - כך תתבצע גם ההגשה במשימות הפרויקט הבאות)

2. לכתוב שכל אחד הגיע ממקום אחר זו לא הכוונה לשונות.

3. צריך סיכונים שנוגעים לפרויקט עצמו, לכם יש סיכונים שמשותפים לכל הפרויקטים.

**Comment by mazmaz2k** [comment]
תוקן  Diversity
הוספו סיכונים שקשורים לפרוייקט
@kob-e

**Comment by YaakovHatam** [comment]
עבודה יפה
