### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [mazmaz2k/jlm.fm#4]
## TODO:
- Please open issue as described
- Please attach here the Client review.

## סיכום פגישתנו:
לא ברור מה צריך לעשות, אין סיכונים, חסר שיתוף פעולה מול הלקוח צריך לשקול pivot אם הלקוח לא מתחייב

**Comment by mazmaz2k** [comment]
@kob-e 
את ההדרכה לפתיחת ISSUE ?? תוכל להראות לי

**Comment by mazmaz2k** [comment]
@kob-e @robi-y 
אי אפשר להגיש client review
אמרנו את זה כבר ונגיד שוב הלקוח לא נפגש איתנו!!!

**Comment by mazmaz2k** [comment]
all bugs fixed @kob-e 
added client review [link](https://github.com/mazmaz2k/jlm.fm/wiki/SRS-Review-Summary#clients-requirements-mail)
