### ISSUE TITLE
Mission 4 - SDS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [mazmaz2k/jlm.fm#47]
- יש לשפר את דיאגרמת המחלקות
- תכנית הבדיקות כוללת בתוכה רק שורה אחד של בדיקות כל השאר לא קשור

**Comment by mazmaz2k** [comment]
class diagram changed  [link](https://github.com/mazmaz2k/jlm.fm/wiki/SDS#crc-cards--class-diagrams)
Initial Test Plan fixed [link](https://github.com/mazmaz2k/jlm.fm/wiki/SDS#initial-test-plan)
@kob-e
